-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1
-- Thời gian đã tạo: Th3 27, 2024 lúc 01:31 PM
-- Phiên bản máy phục vụ: 10.4.28-MariaDB
-- Phiên bản PHP: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `book`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `books`
--

CREATE TABLE `books` (
  `book_id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `author` varchar(255) NOT NULL,
  `category_id` int(11) DEFAULT NULL,
  `other_book_info` varchar(3000) DEFAULT NULL,
  `price` decimal(10,2) DEFAULT NULL,
  `img` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Đang đổ dữ liệu cho bảng `books`
--

INSERT INTO `books` (`book_id`, `title`, `author`, `category_id`, `other_book_info`, `price`, `img`) VALUES
(0, 'tôi thấy hoa vàng trên cỏ xanh', 'Nguyễn Nhật Ánh', 4, '', 79000.00, 'book1.jpg'),
(1, 'Đắc Nhân Tâm', 'Dale Carnegie', 2, '', 69000.00, 'book2.png'),
(2, 'Tabalô Trên đất Á', 'Nhã Nam', 3, '', 59000.00, 'book3.jpg'),
(3, 'Hoàng Tử Bé', 'Antoine De Saint-Exupéry', 4, '', 49000.00, 'book4.jpg'),
(5, 'Warren Buffett: 10 thương vụ thâu tóm bạc tỷ của huyền thoại đầu tư chứng khoán', 'Glen Arnold', 1, NULL, 165000.00, 'sachkinhdoanh2.jpg'),
(6, 'Kỹ năng Lãnh đạo Hiệu quả', 'John C. Maxwell', 1, '', 150000.00, 'sachkinhdoanh3.jpg'),
(7, 'Bí mật Tư duy Triệu phú', 'T. Harv Eker', 1, '', 180000.00, 'sachkinhdoanh4.jpg'),
(8, 'Trong chớp mắt', 'Malcolm Gladwell', 1, '', 135000.00, 'sachkinhdoanh5.jpg'),
(9, 'Đi tìm ý nghĩa cuộc sống', 'Viktor E. Frankl', 1, '', 120000.00, 'sachkinhdoanh6.jpg'),
(10, 'Do Big Things', 'Craig W. Ross - Angela V. Paccione - Victoria L. Roberts ', 1, '', 160000.00, 'sachkinhdoanh7.jpg'),
(11, 'Cuốn sách Bí mật của Người giàu', 'Robert T. Kiyosaki', 1, '', 200000.00, 'sachkinhdoanh8.jpg'),
(12, 'Kinh doanh Thuận lợi', 'Michael E. Gerber', 1, '', 140000.00, 'sachkinhdoanh9.jpg'),
(13, 'Sức mạnh của Thói quen', 'Charles Duhigg', 1, '', 170000.00, 'sachkinhdoanh10.jpg'),
(14, '24 nhân cách của Billy Milligan\n', 'Daniel Keyes ', 3, 'Billy Milligan có thể là bất cứ ai anh ta muốn… ngoại trừ chính bản thân mình\n\nBị giày vò bởi 24 nhân cách khác nhau cùng tồn tại, không ngừng chiến đấu để giành quyền tối cao đối với cơ thể của mình, Billy Milligan đã không còn có thể kiểm soát được hành động của mình nữa. Cuộc chiến bên trong lên đến đỉnh điểm khi anh ta tỉnh dậy trong tù, bị bắt vì tội bắt cóc và hãm hiếp ba phụ nữ. Trong một phiên tòa mang tính bước ngoặt, Billy được tuyên trắng án với lý do mất trí vì đa nhân cách – quyết định lần đầu tiên có trong lịch sử tòa án của Mỹ và nhân loại.\n\nTrong tác phẩm, bạn sẽ được lần lượt gặp từng nhân cách trong câu chuyện có thật gây sốc này. Và bạn sẽ không thể rời mắt khỏi tâm trí của chàng trai trẻ bị tra tấn Billy Milligan cũng như thế giới bị chia cắt, đáng sợ của anh ta.', 200000.00, 'tamlyhoc1.jpg'),
(15, 'Tâm lý hành vi trong đầu tư chứng khoán', 'James Montier', 3, 'Sách này khám phá cách phân tích tâm lý học áp dụng trong đời sống hàng ngày.Ben Graham, được coi là người khai sinh ra trường phái đầu tư giá trị đã từng nói: Vấn đề chính – thậm chí là kẻ thù lớn nhất – mà các nhà đầu tư phải đối mặt có lẽ chính là bản thân mỗi người. Đáng buồn thay, nhận định của Graham vẫn đúng trong bối cảnh ngày nay. Thiên kiến, cảm xúc, tự tin thái quá và lạc quan quá mức chỉ là một số trong rất nhiều xu hướng hành vi có thể khiến các nhà đầu tư mất tiền. Điều may mắn là tài chính hành vi ra đời và thừa nhận thực tế tồn tại yếu tố tâm lý trong quá trình ra quyết định của tất cả các nhà đầu tư. Áp dụng các quy tắc hành vi vào đầu tư và giao dịch giúp nhà đầu tư tránh được một số bẫy tâm lý nghiêm trọng có thể khiến họ phải trả cái giá rất đắt.\n\nTrong cuốn sách này, chuyên gia về tài chính hành vi James Montier nhấn mạnh những xu hướng hành vi nguy hiểm và những sai lầm tâm lý phổ biến mà các nhà đầu tư chuyên nghiệp gặp phải. Tác giả cũng chỉ cho chúng ta cách để nhận ra các bẫy tâm trí này đồng thời tìm ra những nguyên lý của tâm lý học ẩn sâu trong các sai lầm đó. Bên cạnh đó, Montier cũng chỉ cho bạn những gì bạn có thể làm để bảo vệ danh dự.', 300000.00, 'tamlyhoc2.jpg'),
(16, ' Tâm lý học về tiền', 'Morgan Housel', 3, 'Tiền bạc có ở khắp mọi nơi, nó ảnh hưởng đến tất cả chúng ta, và khiến phần lớn chúng ta bối rối. Mọi người nghĩ về nó theo những cách hơi khác nhau một chút. Nó mang lại những bài học có thể được áp dụng tới rất nhiều lĩnh vực trong cuộc sống, như rủi ro, sự tự tin, và hạnh phúc. Rất ít chủ đề cung cấp một lăng kính phóng to đầy quyền lực giúp giải thích vì sao mọi người lại hành xử theo cách họ làm hơn là về tiền bạc. Đó mới là một trong những chương trình hoành tráng nhất trên thế giới.\n\nChúng ta hiếm khi lâm vào hoàn cảnh nợ ngập đầu ư? Biết tiết kiệm để dành cho lúc khốn khó hơn ư? Chuẩn bị sẵn sàng cho việc nghỉ hưu? Có những cái nhìn thiết thực về mối quan hệ giữa tiền và hạnh phúc của chúng ta hơn phải không?\n\nChúng ta đều làm những điều điên rồ với tiền bạc, bởi vì chúng ta đều còn khá mới mẻ với trò chơi này và điều có vẻ điên rồ với bạn lại có khi hợp lý với tôi. Nhưng không ai là điên rồ cả – chúng ta đều đưa ra các quyết định dựa trên những trải nghiệm độc đáo riêng có mang vẻ hợp lý với mình ở bất cứ thời điểm nào.\n\nMục đích của cuốn sách này là sử dụng những câu chuyện ngắn để thuyết phục bạn rằng những kỹ năng mềm còn quan trọng hơn khía cạnh lý thuyết của đồng tiền. Thông qua một tập hợp những thử nghiệm và sai lầm của nhiều năm chúng ta đã học được cách trở thành những nông dân giỏi giang hơn, những thợ sửa ống nước nhiều kỹ năng hơn, và những nhà hóa học tiên tiến hơn. Nhưng liệu việc thử nghiệm và sai lầm có dạy chúng ta trở nên giỏi hơn trong cách quản lý tài chính cá nhân của chính mình không?\n\nNhiều tiền không liên quan nhiều đến việc bạn thông minh như thế nào mà lại liên quan lớn đến cách bạn hành xử. Và cách hành xử thì rất khó để uốn nắn, ngay cả đối với những người thực sự thông minh.\n\nMột thiên tài không kiểm soát được cảm xúc của anh ta có thể dẫn tới một thảm họa tài chính. Điều ngược lại cũng đúng. Những người bình thường không có kiến thức về tài chính có thể trở nên giàu có nếu họ nắm trong tay những kỹ năng hành xử không liên quan đến những thước đo chính thống về trí thông minh.\n\nSự thành công trong tài chính không phải là một lĩnh vực khoa học khó nhằn. Nó là một kỹ năng mềm, nơi mà cách bạn hành xử quan trọng hơn điều mà bạn biết. Trong “Tâm lý học về tiền”, tác giả từng đoạt giải thưởng Morgan Housel chia sẻ 19 câu chuyện ngắn khám phá những cách kỳ lạ mà mọi người nghĩ về tiền bạc và dạy bạn cách hiểu rõ hơn về một trong những chủ đề quan trọng nhất của cuộc sống.', 159000.00, 'tamlyhoc3.jpg'),
(17, 'ART THERAPY - TRỊ LIỆU TÂM LÝ BẰNG NGHỆ THUẬT', 'Leah Guzman', 3, 'ART THERAPY - TRỊ LIỆU TÂM LÝ BẰNG NGHỆ THUẬT\n“Trị liệu tâm lý bằng nghệ thuật của Leah Guzman là kho tàng các công cụ mang tính biến đổi. Cuốn sách sẽ giúp cuộc sống của bạn tốt đẹp hơn.”\n\nKinh tế xã hội ngày càng tiến bộ vượt bậc, lại khiến sức khỏe tâm lý bị đe dọa: hội chứng trầm cảm, lo âu ngày càng tăng cao. Vậy, làm sao để có thể tìm kiếm sự bình yên đích thực? Bạn nghĩ sao nếu áp dụng nghệ thuật vào trị liệu cảm xúc? Để chữa lành những ám ảnh, nghi kỵ, bất an? Để tâm hồn được xoa dịu và hạnh phúc?\n\nKhi mọi nỗ lực dường như đã thất bại, hãy để nghệ thuật dẫn lối bạn. Hãy cùng khám phá sức mạnh chữa lành của trị liệu nghệ thuật qua Trị liệu tâm lý bằng nghệ thuật – một cuốn sách đầy màu sắc. Nghệ thuật không chỉ phơi bày vẻ đẹp, mục đích thực sự ẩn sâu trong đó chính là trở thành một phương tiện điều trị tâm lý giúp đào sâu vào cảm xúc và khám phá cảm nhận và suy nghĩ của mỗi cá nhân.\n\nCuốn sách bao gồm 4 nội dung chính:\n\nCác bài tập để chữa lành và tự khám phá – 75 hoạt động trị liệu nghệ thuật tạo cơ hội để người tham gia tự bày tỏ và cũng là công cụ để đối phó với những rối loạn về tâm trạng và tính cách\n\nNhững nhắc nhở và tương tác mang tính hỗ trợ - Mỗi bài tập bao gồm sự giải thích cụ thể về mục đích của nó và những kết quả mà nó có thể đem lại cùng với những câu hỏi thảo luận sau mỗi hoạt động.\n\nSự hướng dẫn khách quan không kèm theo đánh giá – Chỉ đơn thuần là học những kỹ thuật căn bản của các phương tiện nghệ thuật như vẽ, sơn và điêu khắc – không yêu cầu bất kỳ kinh nghiệm về nghệ thuật nào\n\nDanh sách các công cụ và vật liệu cần thiết – Mỗi phần hướng dẫn thực hành bao gồm danh sách các công vụ và vật liệu cần thiết và lợi khuyên về việc xây dựng không gian nghệ thuật chữa lành.', 149000.00, 'tamlyhoc4.jpg'),
(18, 'Chữa lành cảm xúc bằng năng lượng tích cực', 'Sandra Ingerman', 3, 'Thay đổi nguồn năng lượng để loại bỏ tư duy độc hại và thu hút giá trị tích cực trong cuộc sống\nNăng lượng tiêu cực được tạo ra thông qua niềm tin, suy nghĩ, cảm giác và sự tương tác môi trường, cuộc sống hàng ngày. Những cảm xúc như: tức giận, buồn bã, uất ức, phẫn nộ, bực tức,… hoàn toàn là những cảm xúc bình thường mà tất cả chúng ta đều gặp phải. \nMột sai lầm mà bất kì ai trong chúng ta cũng mắc phải đó là “chỉ quan tâm đến yếu tố thể chất” mà vô tình đẩy “tinh thần, cảm xúc” vào sự lãng quên. Mặc dù “tinh thần” là thứ mà ta không thể nhìn thấy, nhưng cùng với cơ thể và tâm trí, nó tạo nên toàn bộ con người. \n\nBạn có tin rằng xung quanh con người luôn là một sự trao đổi năng lượng. Mỗi người chúng ta lại đóng những vai trò khác nhau trong những cuộc trao đổi này – đôi khi chúng ta là “người phát” năng lượng, đôi khi lại là “người nhận” lại năng lượng. Khi năng lượng mang tính tiêu cực, nó có thể gây hại. Có thể chúng ta không thể ngay lập tức nhận ra điều đó, nhưng những cảm giác tiêu cực có thể độc hại đối với sức khỏe của ta như các chất độc vật chất, chúng đeo bám và gây ra trầm cảm, bệnh tật và kiệt sức. \n\nVới cuốn sách Chữa lành cảm xúc bằng năng lượng tích cực, nhà tâm lý học Sandra Ingerman tiết lộ cho chúng ta những công cụ nhằm đối phó với sự tức giận, sợ hãi, thất vọng và đưa ra các chiến lược để xử lý những suy nghĩ, cảm xúc có hại, thu hút những giá trị tích cực vào cuộc sống. Hãy dùng những phương pháp chữa lành trong cuốn sách này để thay đổi bạn, những người khác và cả thế giới bằng một nguồn năng lượng tích cực hơn bạn nhé!', 99000.00, 'tamlyhoc5.jpg'),
(19, 'Đọc Vị Cảm Xúc Thuyết Phục Bất Kỳ Ai', 'Jessica Taylor', 3, 'Là người phụ trách mục Góc nhìn cho tờ New York Times, tác giả Trish Hall đã dành nhiều năm đắm chìm trong những cuộc tranh luận và những bài viết thể hiện quan điểm. Trong quá trình đó, cô thường xuyên phải tiếp xúc với những câu văn rối rắm, những biệt ngữ khó hiểu và những bài viết chán ngắt. Dựa trên kinh nghiệm mình, Trish Hall đã viết “Đọc vị cảm xúc, thuyết phục bất kỳ ai” để giúp người đọc giao tiếp một cách hiệu quả và thu phục lòng người. Thông qua cuốn sách này, Trish Hall sẽ chỉ cho độc giả cách trình bày ý kiến của mình thật thuyết phục, cho dù bạn đang viết một bài luận cho giáo sư tại trường đại học, một email ứng tuyển việc làm, hay cần thuyết trình về kế hoạch của mình tại nơi làm việc. Mặc dù cuốn sách chủ yếu là về viết lách, tác giả đã chèn thêm các yếu tố tâm lý học để làm luận chứng cho những phương pháp mà cô đưa ra. Hiểu biết về hành vi của con người sẽ rất hữu dụng khi giao tiếp trực tiếp. Trish tin tưởng vào sức mạnh thuyết phục của con chữ vì cô đã chứng kiến rất nhiều những thay đổi tích cực trong cuộc sống được thực hiện nhờ những áng văn hay và thuyết phục. Những chương sách này sẽ đem lại nguồn cảm hứng cho bạn và giúp bạn đủ tự tin để đặt bút viết, lên tiếng về quan điểm của bản thân. Vậy thì, bạn có thể hỏi, có luật lệ nào cho việc tranh luận, tạo niềm tin và thuyết phục người khác nên nghe theo bạn không? Có chứ. Mặc dù rất khó để thay đổi tâm trí, vẫn có những nguyên tắc cơ bản để tạo niềm tin, các kĩ thuật để lôi kéo mọi người về phe bạn, không chỉ trong những cuộc tranh luận mà còn trong cuộc sống. Giống như rất nhiều những luật lệ khác, chúng không dễ để tuân theo. Và cũng giống như tất cả những luật lệ khác, chúng hoàn toàn có thể bị phá vỡ. Bạn có thể vi phạm tất cả những khái niệm và vẫn thuyết phục được ai đó nhìn nhận quan điểm của bạn. Nhưng hãy yên tâm rằng việc sử dụng những biện pháp này, cho dù nó đòi hỏi tính nghệ thuật, kĩ thuật và một sự am hiểu tâm lý con người, sẽ tăng xác suất thành công của bạn.', 50000.00, 'tamlyhoc6.jpg'),
(20, 'Cô độc hướng ngoại hay bình thản hướng nội', 'Christopher Lee', 3, 'Chúng ta thường xuyên sử dụng thuật ngữ “hướng nội” và “hướng ngoại” để miêu tả bản thân và những người xung quanh. Nhưng những từ này thực sự có ý nghĩa gì? Trong số những quan điểm của ta về cách phân loại tính cách, có bao nhiêu điều là sai lầm và định kiến?\n\nDựa trên các nghiên cứu khoa học, cuốn sách “Cô độc hướng ngoại hay bình thản hướng nội” giải mã bản chất hướng nội, hướng ngoại một cách thực tế và dễ hiểu nhất, để ta hiểu hơn về chính mình và xóa bỏ những nhầm tưởng. Đây là một cuốn sách giàu tính thực chiến, đi sâu vào nguồn gốc của các kiểu tính cách, qua đó giải mã tâm lý và hành vi của con người trong những tình huống cụ thể. Chúng ta có thể tận dụng những kiến thức này để cuộc sống của mình thêm phong phú, cũng như thoải mái hơn với cá tính riêng của bản thân và đồng cảm với những người có phong cách sống khác biệt.\n\nCuốn sách giúp bạn:\n\n- Khám phá nguyên nhân tiềm ẩn đằng sau những hành vi và thói quen của bản thân cũng như những người xung quanh. Qua đó, ta sẽ ngừng cố gắng bắt chước người khác và không trở thành một con người trái ngược với bản chất của mình.\n\n- Cảm thấy thoải mái và tự tin với cá tính của riêng ta, được giải phóng khỏi những áp lực và kỳ vọng bất công của xã hội.\n\n- Học cách tự chăm sóc bản thân và quản lý năng lượng của mình đối với những hoạt động xã giao.\n\n- Học cách sống bình thản trong một thế giới ồn ào và gấp gáp, nhưng cũng không bị tách biệt hoàn toàn khỏi cộng đồng.\n\nMỗi chúng ta đều là những cá thể khác biệt. Chấp nhận thực tế đó sẽ giải phóng ta khỏi những kỳ vọng đến từ xã hội, giúp ta thông cảm hơn với những người xung quanh và hòa hợp với thế giới.\n\nHãy nhớ rằng, thang đo hướng nội - hướng ngoại truyền thống là một “sự phân đôi” sai lầm. Mọi người có thể nghiêng hơn về hướng này hay hướng khác, nhưng điều quan trọng là chúng ta vẫn đứng đâu đó ở giữa và có khả năng tận dụng những thế mạnh đến từ cả hai kiểu tính cách. Đó mới là lẽ thường.', 75000.00, 'tamlyhoc7.jpg'),
(21, 'Chuyển Hóa Tâm Thức', 'Elizabeth Garcia', 3, 'Chuyển hóa tâm thức - cuốn sách giới thiệu đến độc giả 18 quy luật tuyệt đối của tâm trí được chia thành 2 phần lý thuyết căn bản và ứng dụng.\n\n- Phần lý thuyết: từ chương 1 đến chương chương 10: Phân tích và nhìn nhận các khía cạnh trong đời sống cũng như xã hội dưới góc nhìn mới thông qua các quy luật tuyệt đối của tâm trí.\n\n- Phần ứng dụng: từ chương 11 đến chương 18: Bàn về tác động của các quy luật tuyệt đối của tâm trí đến các lĩnh vực gần gũi trong cuộc sống như y học, kinh doanh, làm cha mẹ… từ đó rút ra những nhận định đáng giá về khả năng chuyển hóa tâm thức thông qua các quy luật tuyệt đối của tâm trí.\n\nNội dung cuốn sách bàn về những nguồn cơ gây ra các cảm xúc tiêu cực khác nhau, mong muốn kiểm soát chúng của mỗi chúng ta thông qua hành vi phản ứng, phụ thuộc thậm chí là tâm lý giả làm nạn nhân. Qua đó tác giả sẽ cho chúng ta biết tại sao chúng ta lại có những cảm xúc tiêu cực như thế, và chúng ảnh hưởng như thế nào đến cơ thể, tạo ra bệnh tật và gây bối rối trong đời sống công việc lẫn cá nhân của chúng ta.\n\nNgoài ra, ông cũng truy nguyên những tiêu cực này về các quy luật tuyệt đối của tâm trí, hướng dẫn chúng ta cách đối phó với những sự thật đã tạo ra vấn đề để tìm về một cuộc sống an lạc và hạnh phúc.\n\nĐiểm mới mẻ trong cuốn sách này là tác giả tiếp cận vấn đề theo hướng quy nạp, đi từ kết quả, phân tích kết quả và tìm ra nguyên nhân. Từ đó, biết cách trang bị cho mình những “biện pháp” phòng bị dựa trên trải nghiệm.\n\nVới lối viết ngắn gọn và súc tích, Utsumi Satoru sẽ cung cấp cho độc giả những bí kíp thay đổi thái độ, chuyển hóa tâm thức thực sự hữu ích để có thể sắp xếp cuộc sống một cách tốt nhất.', 125000.00, 'tamlyhoc8.jpg'),
(22, ' Bạn Càng Mạnh Mẽ Thế Giới Càng Công Bằng ', 'Patrick King', 3, 'Bạn Càng Mạnh Mẽ Thế Giới Càng Công Bằng\n\"Vượt qua rào cản tâm lý để thành công trong công việc\" - Patrick King\n\n“Bạn cảm thấy công việc của mình thật khốn khổ. Bạn căm ghét đồng nghiệp. Một ngày đi làm của bạn dài đằng đẵng. Bạn không bao giờ có thể tiến xa hơn vị trí hiện tại. Bạn không say mê công việc của mình. Mâu thuẫn cứ mỗi ngày một tăng lên, còn cơ hội và khát khao của bạn thì giảm dần theo tuổi tác.”\n\nCó ai lại chưa từng trải qua những cảm giác như vậy? Nhưng nếu đủ mạnh mẽ, bạn sẽ có thể vượt qua tất cả những khó khăn này, dùng chúng làm bàn đạp để bứt phá tới thành công trong tương lai.\n\nHãy đọc cuốn sách này, thực hành từng bước nhỏ mà tác giả đã vạch ra, rồi thành công sẽ đợi bạn nơi cuối đường. Cuốn sách self-help, truyền cảm hứng này dạy chúng ta cách vượt qua những trở ngại trong cuộc sống hằng ngày để đạt được thành công.\n\nNội dung sách được chia làm 5 chương:\n\nChương 1 - Dừng việc suy nghĩ quá mức\nChương 2 - Chọn thiên hướng hành động\nChương 3 - Tư duy hành động\nChương 4 - Tối đa hóa động lực\nChương 5 - Không trì hoãn', 160000.00, 'tamlyhoc9.jpg'),
(23, 'ENNEAGRAM KHÁM PHÁ BẢN THÂN – GIẢI MÃ TÍNH CÁCH – THẤU HIỂU TÂM LÝ\n', 'Michelle Wilson', 3, '“Mang đến một cái nhìn mới mẻ về hệ thống phân loại tính cách cổ xưa – Enneagram,  với các phần chi tiết về từng loại tính cách cũng như cái nhìn tổng thể về toàn bộ mô hình.”\n\n“Cuốn sách cung cấp những hiểu biết rõ ràng, súc tích, đáng suy ngẫm và sáng suốt về lý thuyết của Enneagram, cũng như đưa ra những ví dụ tuyệt vời để ứng dụng Ennegram vào cuộc sống, tình yêu và công việc, giúp bạn khám phá con người thật của mình và quản lý tốt cảm xúc, phát triển sự nghiệp và hiểu những người xung\n\nquanh.”\n\nEnneagram là gì? Enneagram là mô hình cung cấp một cái nhìn sâu sắc về 9 kiểu hình tính cách riêng biệt theo một cách hiểu nào đó, chúng mở ra lời giải đáp cho câu hỏi “tại sao chúng ta lại làm vậy”.\n\nEnneagram lý giải mọi người nhìn nhận thế giới khác nhau như thế nào, cho phép chúng ta hiểu điểm xuất phát từ những người khác. Theo cách đó, đây là mô hình rất hữu ích cho việc giao tiếp, tương tác tại nơi làm việc và xây dựng mối quan hệ.\n\nCuốn sách cung cấp cho bạn một các nhìn tổng quan rất thực tế về khái niệm Enneagram và cách mô hình này hoạt động. Nó sẽ dẫn bạn đến với nguồn tài liệu để bạn có thể tìm hiểu thêm, bao gồm các bài kiểm tra tính cách mà sẽ giúp bạn khám phá được kiểu hình tính cách của chính mình. Từ đó bạn sẽ khám phá ra cách để ứng dụng những thông tin vào công việc, các mối quan hệ và cuộc sống hằng ngày của bạn.', 190000.00, 'tamlyhoc10.jpg'),
(24, 'DÊ MẮT QUỶ\n', 'Chan Ho Kei ', 4, 'Diệp – nhân vật chính của tác phẩm – là một cậu sinh viên mới chân ướt chân ráo buổi đầu đến ký túc xá một trường đại học để nhận phòng tại Norfolk. Nhưng ngay đêm đầu tiên chuyển vào ký túc xá, cậu và nhóm bạn đã bị “nhắm tới”. Có lẽ họ không nên bàn tán về những truyền thuyết kinh hoàng trong ký túc xá vào lúc nửa đêm, không nên khám phá căn hầm, nơi người ta đồn đại có một quý tộc người Anh đã thực hiện các nghi lễ ma quỷ từ trăm năm trước, càng không nên liều lĩnh chơi trò chơi gọi hồn ở nơi ấy.\n\nNhưng đã quá muộn để quay lại, một bạn nữ trong nhóm bỗng biến mất sau trò chơi, và người bạn nam giúp đỡ tìm kiếm cũng mất tích không để lại dấu vết. Không ai biết được chuyện gì đã xảy ra. Nỗi sợ hãi không tên bao trùm, Diệp mơ hồ cảm thấy một công tắc cấm kỵ nào đó đã được bật lên, cậu chỉ muốn cứu những người bạn đang trong lằn ranh sinh tử  và ngăn chặn “Bảy câu chuyện ma” của Norfolk xảy ra thêm lần nữa!', 199900.00, 'vanhoc1.jpg'),
(25, ' Án mạng dưới tầng hầm', 'Matthew Farrell', 4, '\nMỘT BÁC SĨ TÂM THẦN VẬT LỘN VỚI SỰ TỈNH TÁO CỦA CHÍNH MÌNH KHI BẰNG CHỨNG GIẾT NGƯỜI CHỐNG LẠI ANH TA\n\nĐiều tra viên Susan Adler sẵn sàng khép lại vụ án về một vụ tai nạn xe hơi chết người, nhưng sau khi văn phòng giám định y khoa phát hiện ra dấu vết còn lưu lại từ hành động gây án trên thi thể nạn nhân, cô biết nó đã trở thành một vụ án giết người. Nạn nhân là người vợ giàu có của Randall Brock, một bác sĩ tâm thần nổi tiếng chuyên điều trị cho những bệnh nhân mắc chứng hoang tưởng tàn bạo. Và cứ thế, những nghi ngờ bắt đầu dấy lên trong đầu Susan.\n\nRandall có một quá khứ bạo lực nhưng anh biết mình không giết vợ. Trong nỗi đau buồn tột cùng sau sự ra đi của người vợ thân yêu, anh nhận được lời thăm hỏi từ một người lạ và thông tin chia sẻ về cái chết của vợ anh. Nhưng có một điều kiện: để đổi lấy thông tin từ người đàn ông lạ mặt đó, Randall phải tiết lộ những bí mật đen tối mà anh đã giấu kín trong nhiều năm. Khi hắn gây thêm áp lực và Susan đến gần hơn với những manh mối, Randall bắt đầu nghi ngờ bản thân, tuyệt vọng bám lấy những mảnh ghép trong sự tỉnh táo của mình.\n\nNhững tiết lộ và những sự trùng hợp đáng ngờ đặt ra nhiều câu hỏi trong suốt quá trình điều tra, và các tình tiết ngày càng trở nên mất kiểm soát. Nữ điều tra viên Susan phải chạy đua với thời gian để tổng hợp lại tất cả những tình tiết trước khi quá muộn – trước khi vụ giết người tiếp theo đang đến rất gần nhà cô…\n', 249900.00, 'vanhoc2.jpg'),
(26, 'GARUDA X NAGA - TÌNH YÊU VÀ THÙ HẬN', 'Matthew Farrell', 4, 'Himmapan là một thế giới đặc biệt, đó là ranh giới thế giới của con người và thế giới thiên đường và loài người không bao giờ có thế chạm tới. Các loài sinh vật sống ở đây là những linh thú huyền thoại, chúng được ban cho những sức mạnh diệu kì, có cơ thể quái lạ.\n\nTrong đó, Rắn thần Naga và Chim thần Garuda là hai loài nổi tiếng và “có máu mặt” vì mối thù truyền kiếp giữa chúng.\n\nSinh ra với thân phận một Naga thấp kém, bất kỳ một Garuda nào cũng có thể săn giết cậu. Chiwanthorn đến thế giới loài người để mong có một cuộc sống an ổn, tránh xa móng vuốt của đám Garuda ở Himmapan. Tuy nhiên, có lẽ chú rắn nhỏ đã “tích nghiệp” gì đó quá lớn, nên nghiệt duyên cũng theo đến đây. Nghiệt duyên đó tồn tại trong hình dạng của một Garuda màu vàng kim, là người thừa kế của dòng dõi quyền quý.\n\nTên Garuda “biến thái” này nói rằng hắn yêu Naga mỹ nam, khiến cậu hoang mang, ngỡ ngàng, ngơ ngác. Bạn nói xem rắn nhỏ có nên tin lời tỏ tình của kẻ thù truyền kiếp của gia tộc mình hay không?', 179900.00, 'vanhoc3.jpg'),
(27, 'Verity - Bí mật bị chôn vùi (Colleen Hoover)', 'COLLEEN HOOVER ', 4, 'Lowen Ashleigh là một nhà văn đang gặp khó khăn và đang trên bờ vực phá sản thì nhận được một đề nghị công việc có một không hai trên đời. Jeremy Crawford, chồng của tác giả nổi tiếng Verity Crawford, đã thuê Lowen hoàn thành những cuốn sách còn lại trong một loạt truyện thành công mà người vợ gặp tai nạn của anh không thể hoàn thành.\n\nLowen đến nhà Crawford, sẵn sàng sắp xếp lại các ghi chú và phác thảo trong nhiều năm của Verity, với hy vọng tìm đủ tài liệu để giúp cô ấy có thể bắt đầu công việc của mình. Trong phòng làm việc hỗn loạn, Lowen ngoài ý muốn phát hiện ra một cuốn tự truyện chưa hoàn thành mà Verity có lẽ sẽ không bao giờ cho ai đọc. Từng trang, từng trang của cuốn tự truyện ngập tràn những lời thú tội lạnh thấu tâm can, bao gồm cả hồi ức của Verity về cái đêm mà gia đình cô mãi mãi thay đổi.\n\nLowen quyết định giấu bản thảo vì cô biết rằng nội dung của nó có thể sẽ đánh gục Jeremy, người chồng, người cha đã phải chịu vô vàn đau đớn trong suốt nhiều tháng qua. Nhưng khi tình cảm của Lowen dành cho Jeremy lớn dần, cô nhận ra từng lời trong cuốn tự truyện này đều có thể khiến cô trở thành người hưởng lợi. Suy cho cùng, dù cho Jeremy có chung thủy với người vợ gặp tai nạn của mình đến thế nào, thì sự thật kinh hoàng này chắc chắn sẽ khiến anh không thể tiếp tục yêu cô ta vô điều kiện nữa.\n\nNhưng đến cuối cùng, ai mới là kẻ nói dối, còn sự thật thuộc về ai?', 219900.00, 'vanhoc4.jpg'),
(28, 'Biến tấu đời thường', 'Song Hà ', 4, 'Biến tấu đời thường là tuyển tập những truyện ngắn, những bài viết của tác giả Song Hà, với những câu chuyện rất đời được lấy chất liệu từ đời sống xung quanh tác giả, từ chuyện học đến chuyện ăn, chuyện ngủ, chuyện yêu, chuyện sống… Đọc văn Song Hà, độc giả dễ dàng nhận ra một nhà văn lãng mạn, si mê phái đẹp, dám yêu và sau hết là một hành trình nhọc nhằn kiếm tìm hạnh phúc thông qua cuộc hôn nhân đổ vỡ. Những thứ đó suy cho cùng cũng chỉ là hành trang và cảnh ngộ đời người thông thường có ở bất cứ ai nhưng với Song Hà nó lại đặc biệt cô đúc thành những thiên truyện cuốn hút say mê độc giả.\n\nVăn Song Hà có đủ hỉ, nộ, ái, ố, cả niềm vui, nỗi buồn nhưng dường như ta khó tìm thấy được nỗi buồn đọng trong các trang viết của Song Hà. Lẩn khuất đâu đó một nỗi buồn thân phận nhưng kỳ lạ nó lại là niềm lạc quan sống. Cách kể của Song Hà rất hoạt và tự nhiên nên câu chuyện luôn ngọt ngào dẫn dụ làm mê lịm độc giả. Song Hà kể bằng thứ giọng như có men say và những chi tiết rất đời thường cứ thế hiện lên chân thật và giản dị đúng như cuộc đời vốn có.', 169900.00, 'vanhoc5.jpg'),
(29, 'Mê cung không lối thoát', 'Guy Morpuss', 4, '1. NỘI DUNG\nCuối cùng, chính phủ đã tìm được cách kiểm soát gia tăng dân số.\n\nỞ tuổi 17, mỗi người buộc phải đưa ra một quyết định có thể thay đổi cuộc đời mãi mãi về sau. Có bốn tùy chọn cuộc đời để sống (và chết) như một người máy, công nhân, người khoái lạc và người công xã. Nếu lựa chọn trở thành một người công xã, tâm trí của bạn và bốn người bất kỳ sẽ cùng chia sẻ một cơ thể vật chủ, mỗi người sẽ có được thời gian sống tổng cộng lên đến hàng trăm năm.\n\nNhưng như thế vẫn chưa đủ. Một lời đề nghị hấp dẫn nhưng rủi ro đã được chấp nhận. Một tâm trí mất tích. Bốn kẻ tình nghi. Và liệu có phải chỉ duy nhất một kẻ đứng đằng sau tất cả?', 239900.00, 'vanhoc6.jpg'),
(30, 'Thành phố của những cô gái\n', 'Guy Morpuss', 4, 'Thân mật và giàu cảm giác, nổi loạn với một chút nguy hiểm, Thành phố của những cô gái kể về một câu chuyện tình yêu độc đáo lấy bối cảnh thế giới sân khấu kịch nghệ tại thành phố New York trong những năm 1940. Từ quan điểm của một người phụ nữ lớn tuổi khi nhìn lại tuổi trẻ của mình với cả niềm vui và sự hối tiếc (nhưng chủ yếu là niềm vui), Thành phố của những cô gái khám phá các chủ đề về tình dục và tình yêu của phụ nữ, cũng như sự bình dị của tình yêu đích thực.', 189900.00, 'vanhoc7.jpg'),
(31, 'Sách Tấm Mạng Hoa', 'W. Somerset Maugham', 4, 'Walter – một nhà vi khuẩn học trẻ tài năng, đã kết hôn cùng Kitty, một cô tiểu thư Anh quốc xinh đẹp. Sau đám cưới, họ cùng nhau đi xây dựng cuộc sống mới ở Hương Cảng. Khi Walter phát hiện ra Kitty ngoại tình, anh đã buộc cô phải cùng mình đi đến tâm điểm của một trận dịch tả. Phải rời bỏ cuộc sống xa hoa, bình yên mà cô đã phải bỏ rất nhiều công sức mới có được để chuyển tới một ngôi làng nhỏ, nghèo khó ở Trung Quốc đại lục, liệu thế giới quan của Kitty có thay đổi? Trước những nỗi đau muôn hình vạn trạng của những người xung quanh cũng như chính bản thân mình, liệu lương tâm của cô có thức tỉnh và học được cách yêu thương thực sự không?', 259900.00, 'vanhoc8.jpg'),
(32, 'Thế giới mới nhiệm màu\n', 'Aldous Leonard Huxley ', 4, 'Nội dung chính xoay quanh thế giới hiện đại - văn minh, tất cả mọi thứ đều được đổ bộ bởi khoa học công nghệ. Con người ở thế giới này, con người không được sinh ra theo đúng tự nhiêm mà được ấp theo một cách \"công nghiệp\", được đào luyện bằng những tiếng sấm, bằng việc giật diện. Một thế giới mà con người không được quyết định việc mình sẽ trở thành ai.', 209900.00, 'vanhoc9.jpg'),
(33, 'Sách - Nơi Khu Rừng Chạm Tới Những Vì Sao', 'Glendy Vanderah', 4, 'Đứa trẻ bí ẩn xuất hiện với đôi chân trần, trên người đầy vết bầm tím.\n\nCô bé tự xưng là Ursa, được cử đến từ những vì tinh tú và sẽ chỉ rời đi sau khi chứng kiến đủ năm điều kỳ diệu nơi Địa Cầu. Lo lắng cho đứa trẻ, Jo – một nhà sinh vật học thực địa sống giữa vùng nông thôn Illinois- đành để cô bé ở lại, chỉ tới khi cô biết được sự thật về quá khứ của đứa bé đó.\n\nNhững vấn đề rắc rối bắt đầu xuất hiện khi Jo nhờ đến sự giúp đỡ của Gabriel Nash, một anh chàng hàng xóm ẩn dật, để tìm hiểu về câu chuyện bí ẩn của đứa trẻ kia. Nhưng ở bên cô bé càng nhiều, họ càng nảy sinh những thắc mắc. Vì sao một đứa trẻ không chỉ đọc hết, mà còn hiểu rõ những tác phẩm của Shakespeare? Vì sao những điều tốt đẹp luôn xuất hiện cùng cô bé? Và tại sao Jo và Gabe ngừng tìm kiếm thông tin cô bé trên trang web về trẻ em mất tích?\n\nDù ba người đã có những khoảng thời gian tuyệt vời và tạo ra một mối gắn kết sâu sắc, nhưng họ biết vẫn phải đưa ra những lựa chọn khó khăn. Khi mùa hè sắp trôi qua và Ursa đến gần hơn với điều kỳ diệu thứ năm của mình, quá khứ nguy hiểm của cô bé cũng dần lộ ra. Khi sự thật của họ bị phơi bày, tất cả những bí mật đau đớn cũng sẽ buộc phải hé mở, và số phận ba người họ sẽ bị nắm giữ bởi những vì tinh tú trên cao…', 159900.00, 'vanhoc10.jpg'),
(34, 'Ăn Sạch Sống Xanh Tâm Lành Trí Khỏe\n', 'Darin Olien', 2, 'Hướng dẫn thiết yếu giúp bạn xây dựng chế độ dinh dưỡng lành mạnh, phòng ngừa và chữa lành những tổn thương.\n\nMột cái nhìn toàn diện về chế độ ăn kiêng và dinh dưỡng, một hướng dẫn thiết yếu giúp chúng ta có một cơ thể khỏe mạnh, tràn đầy sinh lực và hạnh phúc mỗi ngày.\n\n \n\nTrong Ăn sạch sống xanh, tâm lành trí khỏe, Darin Olien cung cấp cho chúng ta một cách suy nghĩ hoàn toàn mới về sức khỏe và hạnh phúc bằng cách xác định các động lực sống: Dinh dưỡng chất lượng, Hydrat hóa, Giải độc, Oxy hóa và Kiềm hóa, cho chúng ta biết cách duy trì cân nặng hợp lý, ngăn ngừa ngay cả những căn bệnh nghiêm trọng nhất. Chúng ta luôn được dạy phải xem máu, xương, da, các cơ quan, các nơ-ron thần kinh và tất cả mọi thứ khác một cách riêng rẽ và mỗi bộ phận lại mang đến những vấn đề hay mối lo ngại không giống nhau. Nhưng sự thật là, mỗi một bộ phận nhỏ nhất bên trong cơ thể người, mọi phân tử và tế bào đều phản ứng với năm sinh lực của cuộc sống kể trên. Việc ta cần làm chỉ là làm sao nắm bắt những yêu cầu đó - năm sinh lực của cuộc sống. Và sau đó, ta phải cố gắng hết sức để hoàn thành.\n\n \n\nVới cách tiếp cận toàn diện, tổng thể và duy nhất để chăm sóc sức khỏe, Olien sẽ dạy bạn cách khai thác sức mạnh siêu việt của thực phẩm, nước, oxy và cân bằng độ pH để sống cuộc sống tốt nhất của bạn hôm nay, ngày mai và trong tương lai. Dựa trên những hướng dẫn sử dụng “Cách ăn”, danh sách mua sắm, lời khuyên về “những thứ cần vứt bỏ”, hướng dẫn tạo kế hoạch ăn kiêng lành mạnh, cân bằng và lời khuyên về cách sử dụng thực phẩm bổ sung một cách hiệu quả, Ăn sạch sống xanh, tâm lành trí khỏe là một cái nhìn toàn diện về chế độ ăn kiêng và dinh dưỡng, một hướng dẫn thiết yếu giúp chúng ta có một cơ thể khỏe mạnh, tràn đầy sinh lực và hạnh phúc mỗi ngày.', 199900.00, 'kynang1.jpg'),
(35, 'Ăn xanh sống lành\n', 'Ishihara Yumi', 2, 'ĂN XANH SỐNG LÀNH\n\nUng thư đang ngày càng gia tăng. Y học hiện đại tiến hành điều trị ung thư bằng phẫu thuật, xạ trị, thuốc kháng ung thư... nhưng cuối cùng cũng không mang lại hiệu quả như mong đợi. Có thể thấy, thói quen ăn uống hằng ngày là vô cùng quan trọng và chế độ ăn giàu chất béo, chất đạm như thịt, trứng, sữa, bơ... có ảnh hưởng rất nhiều tới sự phát triển của ung thư.\n\nUng thư là khối u tồn tại từ 10 đến 30 năm nên rất khó thu nhỏ trong thời gian ngắn bằng các biện pháp tự nhiên. Thay vào đó, sau khi trải qua phẫu thuật khi đã phục hồi cả về thể chất lẫn tinh thần, nên áp dụng các biện pháp tự nhiên phù hợp để lọc máu nhằm mục đích ngăn ngừa tái phát và di căn.\n\nMặc dù ung thư được coi là “không rõ nguyên nhân” trong y học hiện đại nhưng cũng không có gì lạ khi cùng một khối u ung thư sẽ phát triển trở lại sau phẫu thuật nếu bạn vẫn cứ duy trì lối sống giống như trước khi phẫu thuật. Bởi nguyên nhân thực sự của ung thư là sự ô nhiễm máu do rối loạn trong thói quen sống như sai lầm trong chế độ ăn uống, luyện tập, sinh hoạt tinh thần.\n\nĂn xanh sống lành là cuốn sách kết hợp giữa kiến thức với các ví dụ thực tế mà tác giả Ishihara Yumi từng gặp, đồng thời mô tả hình thức thực sự của ung thư, các công thức tối đa hóa chế độ ăn uống... Hãy thay đổi cuộc sống và sức khỏe của bạn bằng những hướng dẫn khoa học trong phòng ngừa, điều trị và chữa lành cơ thể bằng những liệu pháp tự nhiên được đề cập cụ thể và chi tiết trong Ăn xanh sống lành.', 249900.00, 'kynang2.jpg'),
(36, 'Kinh Thánh Trẻ Hóa Làn Da - Bí Mật Của Làn Da Không Tuổi', 'VICKY DONDOS', 2, 'Trong Kinh thánh trẻ hóa làn da, tác giả chia sẻ lời khuyên của mình về cách bạn có thể tận hưởng vẻ đẹp tự tin, không cần nỗ lực ở mọi lứa tuổi.\n\nMục đích không phải là để trông trẻ hơn, mà là để nhìn và cảm thấy hài lòng về bản thân và ngoại hình của bạn trong suốt cuộc đời của mình. Trong cuốn sách, tác giả làm sáng tỏ quá trình lão hóa, tiết lộ các sản phẩm đáng đầu tư và chỉ cho bạn cách tạo chương trình cá nhân hóa của riêng bạn, để bạn có thể chăm sóc sức khỏe và ngoại hình của chính mình theo cách phù hợp với bạn, lịch trình của bạn và ngân sách của bạn.\n\nNhững lời khuyên của chuyên gia trong cuốn sách này sẽ giúp bạn:\n\n- Hiểu rõ hơn về làn da của bạn\n\n- Tìm ra phương pháp chăm sóc da phù hợp với bạn\n\n- Tìm hiểu các mẹo lối sống làm tăng vẻ rạng rỡ\n\n- Hiểu rõ hơn về các liệu pháp thẩm mỹ có sẵn cho bạn\n\n- Trên tất cả, hãy trân trọng chính bản thân bạn vẻ đẹp tự nhiên\n\nLão hóa là điều không ai có thể tránh được, song chúng ta có thể làm cho vấn đề ấy trở nên nhẹ nhàng, tích cực hơn.', 179900.00, 'kynang3.jpg'),
(37, 'Sách - Ăn Gì Để Sống - Tập 1 - Booklife', 'Joel Fuhrman MD', 2, 'à một bác sĩ gia đình hơn 30 năm và là tác giả sách bán chạy số 1 của New York Times, Joel Fuhrman, MD sẽ cho bạn biết rằng bác sĩ và thuốc không thể mang lại cho bạn sức khỏe tuyệt vời hoặc sự bảo vệ khỏi bệnh tật và đau khổ. Cách chăm sóc sức khỏe hiệu quả nhất là chăm sóc bản thân đúng cách và bắt đầu bằng việc thay đổi cách ăn uống. Cuốn sách sẽ giúp những người quan tâm đến khoa học dinh dưỡng, sức khỏe và tuổi thọ hiểu rõ suy nghĩ của họ về dinh dưỡng và có thể nêu rõ các yếu tố then chốt và quan trọng nhất để sửa đổi lựa chọn của chính họ.\n\nĂn gì để sống cung cấp cho người đọc kiến thức tốt để họ có thể hướng dẫn những người khác đang vật lộn với sự xung đột về thông tin, sai lệch thông tin và những lời đồn thổi tạo nên nhiều cuộc tranh luận công khai về thực phẩm và chế độ ăn uống. Chỉ thông qua sự hiểu biết về tất cả các khái niệm tối quan trọng về dinh dưỡng của con người, chúng ta mới có khả năng và trở nên quyết đoán trong việc đưa ra các lựa chọn thực phẩm lành mạnh một cách hiệu quả nhất mỗi ngày.\n\nCuốn sách này dành cho bất kì ai hứng thú học hỏi về mối liên quan giữa khoa học dinh dưỡng, chế độ ăn thời hiện đại và sức khỏe hoặc những ai đang tìm kiếm lời khuyên thực tế về việc giảm cân để đạt được sức khỏe tốt nhất. Thông tin trong những trang sách này sẽ thay đổi cuộc đời bạn. Quyết định theo đuổi sức khỏe vượt trội của bạn sẽ bắt đầu một trong những hành trình quan trọng nhất mà bạn có thể thực hiện.', 219900.00, 'kynang4.jpg'),
(38, 'Đơn giản hơn, tinh tế hơn', 'Joel Fuhrman MD', 2, 'Cuốn sách “Đơn giản hơn, tinh tế hơn” chính là món quà mà tác giả Kate Northrup mang đến để giúp chúng ta giải phóng những gánh nặng, những sự kỳ vọng đang đặt lên vai, từ đó dành sự ưu tiên cho bản thân trong việc tự chăm sóc, tự trân trọng, và quan trọng hơn hết là tự yêu thương chính mình. Chỉ khi chúng ta bắt đầu dung hòa được những “thần lực” bên trong, chúng ta mới có thể chăm sóc tốt nhất cho những người chúng ta yêu thương. Tất cả bắt đầu bằng việc phá vỡ mô hình cũ cho rằng “làm nhiều hơn để trở nên có giá trị hơn” và hòa vào dòng chảy của cuộc cách mạng: làm việc ít hơn để làm chính mình nhiều hơn. Khi áp dụng phương pháp này bạn sẽ giải phóng bản thân thoát khỏi những áp lực đang đè nặng trên vai, chăm sóc được cho bản thân nhiều hơn, làm việc hiệu quả, từ đó gặt hái được nhiều thành công trong công việc và cuộc sống.', 169900.00, 'kynang5.jpg'),
(39, 'Đừng ngồi yên lo lắng, hãy rải nắng muôn nơi', 'Joel Fuhrman MD', 2, 'Đừng Ngồi Yên Lo Lắng, Hãy Rải Nắng Muôn Nơi\nPhải chăng, mỗi sớm thức dậy, bạn luôn muốn mỉm cười hào hứng “Say Hi” với cuộc đời? Phải chăng, bạn luôn ước trái tim và trí mình luôn trong trạng thái tích cực? Và phải chăng, bạn luôn muốn bản thân luôn không ngừng tiến về phía, và những người khác cũng vậy?\n\nThông qua cuốn sách giàu cảm hứng Đừng ngồi yên lo lắng, hãy rải nắng muôn nơi của mình, biên tập viên Meaghan B Murphy sẽ chia sẽ tới bạn đọc những bí quyết tìm kiếm những niềm vui sống quý giá mỗi ngày.\n\nCuốn sách Đừng ngồi yên lo lắng, hãy rải nắng muôn nơi tổng hợp hướng dẫn thực tế nhất của Murphy giúp bạn tạo ra những khoảnh khắc tốt đẹp, dù đang bị nhấn chìm trong trăm ngàn áp lực cuộc sống. Cụ thể, cuốn sách giúp ta:\n\nNuôi dưỡng lòng biết ơn.\nKết nối có ý nghĩa với những người xung quanh bạn.\nHọc cách nói không - để bạn có thể lấp đầy ngày của mình bằng những điều quan trọng nhất đối với bạn.\nNạp năng lượng khi bạn cần.\nLan truyền trách nhiệm tích cực đến những người khác, khiến thế giới trở thành một nơi hạnh phúc hơn, lành mạnh hơn.\nCuốn sách đầy cảm hứng và sức mạnh này cung cấp một kế hoạch chi tiết để cảm thấy bớt căng thẳng và thực sự tận dụng tối đa thời gian mỗi ngày của bạn.', 239900.00, 'kynang6.jpg'),
(40, 'Reiki - Nghệ thuật chữa lành bằng năng lượng\n', 'Joel Fuhrman MD', 2, 'REIKI - NGHỆ THUẬT CHỮA LÀNH BẰNG NĂNG LƯỢNG\n\n“Reiki là một trong những phương pháp chữa lành bằng năng lượng đơn giản và mang tính trực giác nhất. Là kỹ thuật chữa lành bằng năng lượng mang tính thực hành, hiệu quả, nhẹ nhàng, có nguồn gốc từ Nhật Bản, và ai cũng có thể học được.”\n\n“Giúp khai phá và phát triển năng lực bí ẩn trong bạn, giúp chữa lành những tổn thương, cân bằng tâm trí và cảm xúc.”\n\nMọi người đều có trực giác, và nhiều người trong chúng ta có khả năng ngoại cảm. Chúng ta có thể phát triển những năng lực này nếu tập trung và hành động. Nếu bạn sở hữu tài năng tiềm tàng mạnh mẽ, đó sẽ là một phần mục đích sống của bạn và thật sáng suốt khi mài giũa chúng.\n\nViệc học Reiki có thể khai phá sự nhạy cảm tiềm tàng và năng lực ngoại cảm trong bạn. Nếu bạn đã sở hữu năng lực ngoại cảm và trực giác, trải qua những cấp độ thực hành Reiki, có thể bạn sẽ sở hữu nhiều năng lực hơn thế.\n\n \n\nNăng lực thấu cảm và ngoại cảm là bộ công cụ mạnh mẽ, hiệu quả của những người chữa lành. Nhận biết và phát triển năng lực thấu cảm và ngoại cảm nên là một phần của quá trình học tập Reiki. Nếu bạn đã biết mình có năng lực thấu cảm và ngoại cảm, việc học Reiki sẽ khai phá năng lực ấy sâu hơn và nhanh hơn. Cả năng lực chữa lành và ngoại cảm là những kết quả đi kèm cùng với sự phát triển về tinh thần, và Reiki là con đường hiệu quả giúp trưởng thành về tinh thần. Năng lực ngoại cảm tự nhiên sẽ tăng lên khi chúng ta trưởng thành về tinh thần. Nhưng, luôn có những va chạm, xung đột trên con đường ấy, đòi hỏi sự hòa hợp và phát triển, và Reiki giúp ích rất nhiều.', 189900.00, 'kynang7.jpg'),
(41, 'Rèn luyện tư duy độc lập', 'Joel Fuhrman MD', 2, 'Cuốn sách Rèn luyện tư duy độc lập viết về những người phụ nữ có tư duy độc lập, sống mạnh mẽ, tự chủ trong bất kỳ hoàn cảnh nào của cuộc sống. Cuốn sách đề cao sự độc lập trong tư duy, suy nghĩ, trong cách giải quyết vấn đề, cho rằng sự độc lập sẽ mang lại cho bạn thành công rực rỡ. Những người nỗ lực theo đuổi ước mơ hãy cứ kiên trì từng bước, chắc chắn bạn sẽ đạt được ước mơ của mình. Chúc cho tất cả những con đường vòng bạn từng đi qua đều có thể tở thành chiếc cầu vồng rực rỡ nhất!', 259900.00, 'kynang8.jpg'),
(42, '\nSách - Chậm để trải nghiệm, Chậm để tận hưởng, Chậm để trưởng thành - Booklife', ' Chu Thanh', 2, 'Những lo lắng hay hy vọng về cuộc đời có lẽ ẩn hiện trong những nhân viên công sở tan làm, ngồi ở một con hẻm nhỏ ăn một bát cháo thịt băm; cũng có thể là tấm hình thần tượng được treo trên tường trong những phòng kí túc xá cũ; hay cũng có thể là một ngày lạc trong rừng sâu ngồi trò chuyện với vị hòa thượng già.\nCũng giống như khi chơi bàn cát, bạn có đáp án tham khảo, nhưng không có đáp án chính xác. Lựa chọn thế nào sẽ quyết định bạn có những trải nghiệm ra sao.\n\nTrên thực tế, bạn không cần phải cố chen chân vào những nơi xô bồ, bon chen; càng không cần vội vã làm việc ở những ngành nghề áp lực nhất khi vừa mới tốt nghiệp; cũng không cần vội vàng xem mắt, kết hôn khi mới vừa hai mươi xuân xanh.\n\nChỉ có bạn, người sống giữa cuộc đời và các mối quan hệ xã hội chân thực, mới có thể hiểu được liệu những điều này có đáng hay không, có cần thiết hay không.”\n\nSau tuổi đôi mươi, bạn chính là người trưởng thành của chính mình.', 209900.00, 'kynang9.jpg'),
(43, 'Dinh Dưỡng Thai Kỳ', 'Lily Nichols', 2, '“Dinh dưỡng thai kỳ” giống như một cuốn bách khoa toàn thư về chế độ dinh dưỡng cho phụ nữ trong thời kỳ mang thai, với lượng kiến thức toàn diện về những vấn đề mà bất cứ một người phụ nữ trong thai kỳ nào cũng quan tâm, như Xét nghiệm, Độc tố thường gặp, Thực phẩm bổ sung và Thời kỳ sau sinh. Không giống như những cuốn thai giáo khác, “Dinh dưỡng thai kỳ” sẽ giải thích cặn kẽ những vấn đề đang gây tranh cãi trong nền khoa học dinh dưỡng hiện đại và biến những giáo điều thông thường thành những điều mới mẻ. Cuốn sách chính là bước ngoặt trong khoa học dinh dưỡng và chăm sóc y tế.\n', 159900.00, 'kynang10.jpg'),
(44, 'Blockchain: Bản chất của Blockchain, Bitcoin, tiền điện tử, hợp đồng thông minh và tương lai của tiền tệ\n', '.', 5, 'Tiền điện tử, với đại diện tiêu biểu nhất là Bitcoin, đang là mối quan tâm hàng đầu của giới tài chính toàn cầu. Khả năng thanh toán bằng tiền ảo mở ra hàng loạt tiềm năng cho thương mại và thay đổi toàn diện thói quen tiêu dùng của con người. Hạt nhân của công nghệ hứa hẹn rung chuyển thế giới này được gọi là Blockchain.\n\nBlockchain được giới công nghệ đánh giá là phát kiến vĩ đại nhất sau khi mạng Internet ra đời. Ứng dụng phổ biến nhất của nó là các loại tiền điện tử nổi tiếng (Bitcoin, Ethereum, Ripple...) đang làm mưa làm gió trên thị trường. Nhưng nghịch lý là, lại rất ít người nắm được bản chất của tiền điện tử và Blockchain. Rốt cuộc, Blockchain là gì? Nó hoạt động như thế nào? Blockchain thật sự là một đột phá trong công nghệ hay chỉ là một trào lưu nhất thời? Blockchain có liên hệ như thế nào với Bitcoin? Liệu Blockchain có nắm giữ tiềm năng thay đổi thế giới?...\n\nThực chất, những bài viết cung cấp thông tin về Blockchain và tiền điện tử không thiếu trên các website hay mạng xã hội, nhưng lại chưa đủ tính bao quát và còn khó tiếp thu. Đó là lý do cuốn sách “BLOCKCHAIN: Bản chất của Blockchain, Bitcoin, tiền điện tử, hợp đồng thông minh và tương lai của tiền tệ” của Mark Gates ra đời. Gates cung cấp một bản tóm lược dễ hiểu nhất, cung cấp nền tảng thiết yếu cho những người mới bắt đầu và cả những ai muốn nghiên cứu sâu hơn về công nghệ Blockchain và tiền ảo. Đọc cuốn sách này, bạn sẽ hiểu được Blockchain dưới nhiều khía cạnh, trong đó không chỉ có những lời ngợi khen mà còn không thiếu các chỉ trích, bình luận trái chiều.', 199900.00, 'dautu1.jpg'),
(45, '138 lời khuyên đắt giá từ ông trùm đầu tư Charlie Munger\n', 'Charlie Munger', 5, 'Charlie Munger vừa là người bạn thân thiết, vừa là cánh tay phải đắc lực của tỷ phú Warren Buffett, đồng thời là Phó Chủ tịch đầy quyền năng của Berkshire Hathaway. Nhiều người đã gọi Charlie Munger là \"ông trùm\" trong lĩnh vực đầu tư, bởi ông sở hữu tư duy vượt trội và năng lực nắm bắt cơ hội hiếm ai bì kịp. Chính Charlie Munger đã truyền cảm hứng cho vô số nhà đầu tư, cả những kẻ lọc lõi nhất lẫn những người mới vào nghề, để họ thành công rực rỡ như ông và người bạn thân Warren Buffett.\n\n\"138 lời khuyên đắt giá từ ông trùm đầu tư Charlie Munger\" là bản tổng hợp chi tiết và toàn diện những triết lý và tư vấn đầu tư của người đàn ông thông tuệ này. Qua 138 lời khuyên “vàng” có trong sách, chúng ta sẽ hiểu được tại sao một người được đào tạo để trở thành một luật sư, người chưa từng tham gia bất kỳ một lớp học về kinh tế, tiếp thị, tài chính hay kế toán nào lại có thể trở thành một trong những doanh nhân vĩ đại nhất, một nhà đầu tư thiên tài của thế kỷ 20, 21.\n\nCuốn sách này dành cho những ai đang tìm hiểu về đầu tư, đặc biệt là đầu tư chứng khoán. Nhưng nếu bạn đơn thuần muốn tìm kiếm một người dẫn dắt để cải thiện khả năng phân tích, nâng cao kỹ năng tư duy thì “138 lời khuyên đắt giá từ ông trùm đầu tư Charlie Munger” sẽ trợ giúp cho bạn. Những lời khuyên của Charlie không chỉ về kinh doanh, ông còn đề cập đến những triết lý trong cuộc sống của chính mình, về giáo dục và mưu cầu hạnh phúc trong một thời đại đầy biến động.', 249900.00, 'dautu2.jpg'),
(46, '6 Thói quen của người làm việc hiệu suất cao\n', 'Charlie Munger', 5, 'Tất cả chúng ta đều muốn có hiệu suất cao trong mọi lĩnh vực cuộc sống, từ học tập, làm việc, đến mở rộng mối quan hệ hay xử lý các vấn đề cá nhân. Nhưng ta phải làm những gì, phải hình thành những thói quen nào để đạt được thành công lâu dài và hạnh phúc bất kể tuổi tác, nghề nghiệp, ưu điểm hay tính cách của ta?\n\nBrendon Burchard – một trong những nhà huấn luyện uy tín nhất thế giới hiện nay về vấn đề phát triển bản thân đã chỉ ra 6 thói quen cần có để tối ưu hiệu suất làm việc. Đó là:\n\n- Tìm kiếm sự sáng suốt\n\n- Sản sinh năng lượng\n\n- Tăng cường sự cần thiết\n\n- Tăng cường năng suất\n\n- Phát triển tầm ảnh hưởng\n\n- Thể hiện lòng can đảm\n\nCuốn sách “High performance habits – 6 thói quen của người làm việc hiệu suất cao” diễn giải chi tiết cách thức để thực hành những thói quen này. Cuốn sách đã tổng hợp những nghiên cứu trong 20 năm của tác giả Brendon Burchard từ hoạt động huấn luyện của mình. Đây là các tổng kết đắt giá nhất có được nhờ các cuộc khảo sát, phỏng vấn tiêu chuẩn và các công cụ đánh giá chuyên nghiệp về những người có hiệu suất cao trên toàn thế giới. Tác phẩm hé lộ một người nên nắm bắt điều gì để trở thành một người hiệu suất cao – có thể tạo ra những cấp độ ngày càng tăng của hạnh phúc, sức khỏe và thành công lâu dài.\n\nNếu bạn muốn hình thành một thói quen nào mới để thành công nhanh hơn, hãy chọn những thói quen trong cuốn sách này. Bất cứ ai cũng có thể thực hành chúng, và bạn sẽ thấy những điều phi thường xảy ra trong cuộc sống, các mối quan hệ và sự nghiệp. Nếu bạn muốn đạt được nhiều thứ hơn, lãnh đạo tốt hơn, phát triển kĩ năng nhanh hơn, hoặc đạt được nhiều niềm vui và tự tin hơn, “High performance habits – 6 thói quen của người làm việc hiệu suất cao” sẽ trợ giúp đắc lực cho bạn.', 179900.00, 'dautu3.jpg'),
(47, 'BITCOIN - Bong bóng tài chính hay tương lai của tiền tệ', 'Charlie Munger', 5, '“Tất cả mọi người đều cần tìm hiểu thông tin về Bitcoin. Bởi vì nó có tiềm năng trở thành một trong những thành tựu quan trọng nhất của thế giới.” (Leon Luow, người được đề cử giải Nobel hoà bình)\n\nTuy vậy, tất cả những dự đoán tích cực về Bitcoin mới chỉ dừng lại ở mức “tiềm năng”. Với sự bất ổn của các đồng tiền điện tử, nhiều chuyên gia và đông đảo dư luận còn khẳng định Bitcoin không hơn gì một bong bóng tài chính cỡ đại.\n\nLiệu Bitcoin có thể thay đổi thế giới tài chính và tiếp tục phát triển, tác động đến ngành công nghiệp và các lĩnh vực khác của đời sống?\n\nLiệu Bitcoin có chính thức trở thành một loại tiền tệ mới, một công nghệ hoàn toàn đột phá, có khả năng tạo ra cuộc cách mạng lớn như cách Internet đã biến đổi thế giới?\n\nLiệu các dự đoán về tiềm năng của tiền điện tử có trở thành sự thực, hay thực chất đây chỉ là những đồn đại thổi phồng?\n\n\"BITCOIN - Bong bóng tài chính hay tương lai của tiền tệ\" của tác giả Mark Gates cung cấp một cái nhìn toàn diện và những hiểu biết đầy đủ về Bitcoin, giúp những ai mong muốn có góc nhìn đa chiều về đồng tiền này có thêm một tài liệu tham khảo đáng tin cậy.\n\nBạn không cần phải có máy vi tính hoặc nền tảng tài chính để hiểu được cuốn sách này, vì nó được viết để những người mới bắt đầu chưa có kiến thức sâu về Bitcoin cũng có thể dễ dàng tiếp cận. Trong trường hợp bạn đã quen thuộc với cách vận hành của tiền điện tử, cuốn sách của Mark Gates cũng không khiến độc giả thất vọng, với sự xuất hiện của những chương sách trình bày các chủ đề nâng cao đầy hấp dẫn.\n\n*Sách cùng tác giả đã xuất bản: “BLOCKCHAIN – Bản chất của Blockchain, Bitcoin, tiền điện tử, hợp đồng thông minh và tương lai của tiền tệ”', 219900.00, 'dautu4.jpg'),
(48, 'Bussiness plan - Lập kế hoạch kinh doanh chuyên nghiệp\n', 'Charlie Munger', 5, 'Khi bắt đầu thành lập doanh nghiệp hay mở rộng quy mô hoạt động, lập ra một bản kế hoạch kinh doanh là bước đi đầu tiên không thể thiếu. Business Plan: Lập kế hoạch kinh doanh chuyên nghiệp cung cấp những hướng dẫn chuyên môn và thực tiễn để chúng ta vạch ra một chương trình hành động hiệu quả, súc tích mà vẫn đảm bảo tính toàn diện. Nếu như muốn khơi dậy động lực, thuyết phục mọi người đầu tư tiền bạc, công sức và thời gian vào doanh nghiệp của bạn, đây chính là cuốn sách bạn cần đọc và áp dụng.\n\nBản kế hoạch kinh doanh càng được chuẩn bị kỹ lưỡng và lôi cuốn, bạn càng có nhiều cơ hội ghi điểm trước các nhà đầu tư và khách hàng tiềm năng. Thông qua những hướng dẫn từng bước và các ví dụ cụ thể, tác giả Brian Finch sẽ trợ giúp bạn xây dựng một bản kế hoạch kinh doanh thu hút mọi tổ chức tài chính, thuyết phục họ đầu tư và hỗ trợ bạn trong công cuộc mở rộng kinh doanh. Thông qua cuốn sách, bạn sẽ biết cách:\n\n- Tạo ra bản kế hoạch kinh doanh hoàn chỉnh\n\n- Xây dựng chiến lược hoạt động cho doanh nghiệp\n\n- Đưa ra dự báo kinh doanh sát với thực tế thị trường\n\n- Làm rõ các thông tin tài chính quan trọng\n\n- Lập kế hoạch về nhân sự và phòng tránh rủi ro\n\nTrong quá trình xây dựng kế hoạch, việc tham khảo ý kiến chuyên gia là điều cần thiết, nhất là về những vấn đề ngân sách và pháp lý, nhưng với tư cách là chủ doanh nghiệp, bạn phải là người đóng góp chính và hiểu tường tận mỗi chi tiết kinh doanh. Hãy xem việc lập kế hoạch giống như truyền đạt câu chuyện của mình một cách ấn tượng và chân thực, nhằm thuyết phục người đọc đồng hành với bạn trên con đường chinh phục các mục tiêu.', 169900.00, 'dautu5.jpg');
INSERT INTO `books` (`book_id`, `title`, `author`, `category_id`, `other_book_info`, `price`, `img`) VALUES
(49, 'Charlie Munger - Phương Pháp Đầu Tư Giá Trị\n', 'Tren Griffin', 5, 'Nhận xét của người nổi tiếng:\n\n“Charlie Munger thường được xem là nhà đầu tư giỏi nhất thế giới. Trí tuệ phi phàm của ông - mạng lưới hiểu biết về các lĩnh vực riêng biệt - là một cách hiệu quả để đạt được kết quả đầu tư vượt trội. Nếu không có nó, việc đạt được thành công trên thị trường - hay bất cứ nơi nào khác - cũng chỉ là một sự may mắn ngắn ngủi.”\n\n- Robert Hagstrom, tác giả của cuốn The Warren Buffett Way (Phương pháp đầu tư Warren Buffett) và Investing: The Last Liberal Art (tạm dịch: Đầu tư: Môn nghệ thuật tự do cuối cùng).\n\n“Griffin đã tóm gọn các ý tưởng cơ bản của Munger, tổng hợp lại những bình luận mà ông đã đưa ra ở nhiều nguồn khác nhau trong suốt nhiều năm. Đầy trí tuệ, chuyên sâu và bổ ích - đồng thời cũng mang lại niềm vui cho người đọc.”\n\n- Lawrence Cunningham, tác giả của cuốn Berkshire Beyond Buffett: The Enduring Value of Values (tạm dịch: Berkshire ngoài Buffett: Giá trị lâu bền của các giá trị)\n\n“Điều gì sẽ xảy ra nếu tôi nói với bạn rằng nhà đầu tư vĩ đại nhất thế giới cũng là một trong những tác giả và nhà tư tưởng xuất sắc nhất trong lĩnh vực này? Và điều gì sẽ xảy ra nếu có một cuốn sách bao hàm tất cả những bình luận sâu sắc nhất của ông, được tổng hợp lại thành những bài học mà chúng ta đều có thể nắm bắt? Tôi rất vui mừng được nói với bạn rằng cuốn Charlie Munger của Tren Griffin chính là một tác phẩm như vậy.”\n\n- Joshua M. Brown, Giám đốc điều hành của Ritholtz Wealth Management, tác giả của cuốn Backstage Wall Street (tạm dịch: Cửa hậu của phố Wall).', 239900.00, 'dautu6.jpg'),
(50, 'CUỘC CHIẾN PHỐ WALL\n', 'Tren Griffin', 5, 'Kể từ thời khai sinh chế độ Công hòa , người Mỹ đã phản bận tâm với các câu hỏi về ngân hàng , tiền và tín dụng, với quyền lực của chúng ta  với vấn đề kép - làm thế nào để tạo ra các tập đoàn khi trong ki đồng thời hạn chế sức phá hoại của của chúng. Từ giá trị của tiền tệ trong túi mọi người đến bản chất của tiền tệ và mối liên hệ của nó với tiền giấy và kim loại , các nhà kinh tế , nông dân và các nhà máy đã liên tục đưa ngành ngân hàng vào trung tâm chính trị của Mỹ. Không nhiều chủ đề gây ra tranh cãi hay kiên kết chặt chẽ cuộc chiến , nề chính trị và cuộc sống hằng ngày của nước Mỹ đến vậy.\n\nCuốn sách cung cấp lịch sử ngắn gọn về tàu chính nước Mỹ, hình thức tập đoàn và tập trung vào các cuộc khủng hoảng ngày càng trầm trọng kể từ năm 1929, khi bối cảnh pháp lý mà chúng ta biết phần lớn là hình thành: cuộc khủng hoảng tiết kiệm của thập niên 1980, sự sụp đổ của gã khổng lồ ngành năng lượng Enron với một loạt vụ bê bối kế toán , và cuộc khủng hoảng nhà đất với cái tên Đại suy thoái. Mỗi thảm họa đều phát triển từ khủng hoảng trước đó. Việc kể các câu chuyện trên theo trình tự sẽ giúp mình họa mối tương quan giữa chúng và cung cấp cho bạn những hiểu biết cần thiết để lường trước và chuẩn bị tốt hơn cho cuộc khủng hoảng tài chính tiếp theo.', 189900.00, 'dautu7.jpg'),
(51, 'NGHỆ THUẬT PHÁT TRIỂN BẢN THÂN\n', 'Brian Tracy', 5, 'Với cuốn sách Nghệ thuật phát triển bản thân, Dan Strutzel và Bryan Tracy sẽ bàn về cách phát triển bản thân thông qua những kỹ năng tạo ảnh hưởng, từ đó giúp bạn tạo ra những kết quả đáng kinh ngạc như mối quan hệ cá nhân hạnh phúc hơn, bán hàng tốt hơn, tạo ra những mối quan hệ đối tác có lợi hơn cũng như hoàn thành những mục tiêu quan trọng nhất đối với bạn. Không chỉ dừng lại ở đó, cuốn sách còn giúp bạn thấy rằng thật sự có khoa học về tầm ảnh hưởng, một cơ sở khoa học đã được kiểm định và chứng minh nhiền lần, không phải chỉ trong vài năm hay vài thập kỉ, mà cả nghìn năm nay. Mục tiêu của cuốn sách này là mang đến cho bạn thật nhiều sự thật đã được kiểm chứng về tầm ảnh hưởng, loại bỏ những lời đồn đoán cũng như mớ lý thuyết nửa mùa, và đem đến cho bạn một kho tàng ý tưởng để có thể trở thành nguồn cảm hứng trong chính cuộc đời mình cũng như cuộc đời của những người mà bạn quan tâm', 259900.00, 'dautu8.jpg'),
(52, 'Nói Sao Cho Khách Hàng Thích - Bán Sao Cho Khách Hàng Mua\n', 'Jeb Blount', 5, 'Trong thời điểm mà thị trường biến động như hiện nay, việc bán hàng trở nên rất khó khăn. Người mua trở nên khan hiếm và chúng ta phải cạnh tranh quyết liệt với đối thủ để ký được hợp đồng với một số ít người vẫn muốn mua hàng. Những vị khách tiềm năng không muốn gặp bạn, sự phản đối ngày càng gay gắt hơn, khách hàng đột ngột hủy bỏ đơn đặt hàng hoặc gây áp lực buộc bạn phải giảm giá.\n\nTuy nhiên, bạn vẫn phải đáp ứng chỉ tiêu bán hàng của bản thân. Nếu không, thu nhập của bạn sẽ bị ảnh hưởng và khoản tiền tiết kiệm của bạn sẽ bốc hơi trong một thị trường đang rơi tự do. Trong cuốn sách Nói sao cho khách hàng thích - Bán sao cho khách hàng mua, chuyên gia bán hàng Jeb Blount cung cấp một kế hoạch chi tiết và tối quan trọng để bạn duy trì động lực, giữ cho danh sách khách hàng của bạn luôn dồi dào, đảm bảo giữ chân khách hàng và củng cố sự nghiệp của bạn trong những thời điểm đầy biến động.\n\nJeb cung cấp cho bạn 55 lời khuyên, kỹ thuật và chiến thuật dễ sử dụng đã được kiểm chứng qua thời gian - những điều có thể giúp bạn đứng đầu khi mọi người khác đều đang thất bại. Bạn sẽ khám phá ra:', 209900.00, 'dautu9.jpg'),
(53, 'Kỷ nguyên tiền điện tử\n', 'Paul Vigna và Michael J. Casey', 5, 'Từ một ảo ảnh biến thành hiện thực, từ một ý niệm trở thành hành động; và trong chưa đầy một thập kỷ, Bitcoin cùng nhiều loại tiền kỹ thuật số đã khuấy đảo cả hành tinh. Mới hôm trước, mọi thứ vẫn còn bình lặng. Nhưng chỉ sau một đêm, Bitcoin khiến toàn bộ thế giới xung quanh bạn rung chuyển. Từ “Bitcoin” xuất hiện trên mọi tít báo bạn lướt qua, và làm bùng nổ những cuộc tranh luận vô tận.\n\nNgười ta có rất nhiều cách gọi tên Bitcoin. Nó là tiền điện tử, tiền ảo, hay tiền mật mã (cryptocurrency). Bạn có thể sử dụng nó để mua bất cứ thứ gì, từ cà phê đến ô tô. Nhưng kể cả khi thế giới đang đổ xô vào cuộc đầu tư qui mô toàn cầu này, vẫn thật khó để trả lời: Bitcoin thực sự là gì, và tại sao mọi người lại cần quan tâm đến Bitcoin, cũng như công nghệ đằng sau nó - công nghệ Blockchain?\n\nPaul Vigna và Michael J. Casey - bộ đôi phóng viên kinh tế dạn dày kinh nghiệm của The Wall Street - đã thực hiện cuốn sách “Kỷ nguyên tiền điện tử” để giúp độc giả có những hiểu biết cụ thể về làn sóng tiền điện tử đang dâng lên mạnh mẽ hơn bao giờ hết. Nguồn gốc, sự phát triển, chức năng, tiềm năng... - tất cả những gì bạn cần biết về tiền ảo, cũng như việc nó đang thách thức trật tự kinh tế toàn cầu ra sao - sẽ được phân tích trong cuốn sách này. Tác phẩm cung cấp bức tranh toàn cảnh về các hình thái tiền tệ, từ đó giải thích cho bạn hiểu lý do các chuyên gia mã hóa lại nảy ra ý tưởng về Blockchain và Bitcoin, và vì sao lại có nhiều người ủng hộ hệ thống tiền tệ mới này đến thế.', 159900.00, 'dautu10.jpg'),
(54, '52 Thí Nghiệm Khoa Học Siêu Thú Vị Kích Thích Trí Sáng Tạo', 'NXB: Thế giới', 6, 'Cuốn sách gồm 52 thí nghiệm về Vật Lý, Hóa học và Sinh học. Trẻ sẽ được tìm hiểu những hiện tượng hết sức quen thuộc của cuộc sống như hiệu ứng nhà kính, chuyển động bằng phản lực, áp suất khí quyển,… Những thí nghiệm trong cuốn sách “52 Thí nghiệm Khoa Học siêu thú vị kích thích trí sáng tạo” sẽ giúp các nhà khoa học nhí rèn tư duy phản biện và kĩ năng giải quyết vấn đề.', 199900.00, 'thieunhi1.jpg'),
(55, '52 Thí Nghiệm Steam Siêu Thú Vị Kích Thích Trí Sáng Tạo\n', 'NXB: Thế giới', 6, 'Cuốn sách gồm 52 thí nghiệm về Khoa học, Công nghệ, Kỹ thuật, Nghệ thuật và Toán học (Steam). Trẻ sẽ được học cách chế tạo nguồn điện đơn giản, tự làm rô-bốt đồ chơi, hay tự chế tạo giấy và màu vẽ,… Cuốn sách “52 Thí nghiệm STEAM siêu thú vị kích thích trí sáng tạo” sẽ phát huy tối đa khả năng sáng tạo của các nhà sáng chế nhí.\n\n\n', 249900.00, 'thieunhi2.jpg'),
(56, '52 Thí Nghiệm Vũ Trụ Siêu Thú Vị Kích Thích Trí Sáng Tạo\n', 'NXB: Thế giới', 6, 'Cuốn sách gồm 52 thí nghiệm giúp trẻ khám phá từ bầu trời đêm huyền bí, đến dải ngân hà xinh đẹp và xa hơn nữa là vũ trụ bao la. Trẻ sẽ được học cách tự chế tạo kính thiên văn đơn giản, tự quan sát vết đen Mặt Trời, tìm kiếm những chòm sao trên bầu trời đêm,… Cuốn sách “52 Thí nghiệm Vũ Trụ siêu thú vị kích thích trí sáng tạo” chắc chắn sẽ làm thỏa mãn trí tò mò của các nhà thiên văn nhí.\n\n\n', 179900.00, 'thieunhi3.jpg'),
(57, 'Câu Chuyện Về Khổng Tử - Giá Trị Của Lòng Trung Thực\n', 'NXB: Thế giới', 6, 'Cuốn sách là câu chuyện tóm tắt về cuộc đời Khổng Tử, một nhà tư tưởng, một người thầy vĩ đại của Trung Hoa, từ lúc sinh thời đến khi về già. Nội dung cuốn sách đi sâu vào việc khắc họa tư tưởng của ông về lòng trung thực với những câu chuyện nhỏ trong cuộc đời của Khổng Tử cũng như cách ông truyền bá tư tưởng về lòng trung thực của mình cho học trò và những người xung quanh.\n\n“Câu chuyện về Khổng Tử - Giá trị của lòng trung thực” là một cuốn sách giúp các bạn nhỏ hiểu rõ hơn về cuộc đời cũng như tư tưởng của Khổng Tử. Ông là người học rộng, tài cao. Bất cứ việc gì, ông cũng để ý xem xét rất kỹ lưỡng cho đến khi hiểu rõ mới thôi. Những câu chuyện trong cuốn sách được xây dựng những sự kiện diễn ra trong cuộc đời Khổng Tử. Thông qua đó, các bạn nhỏ sẽ hiểu hơn về giá trị và ý nghĩa của lòng trung thực. Cuốn sách đồng thời cũng giúp các em trau dồi đạo đức và tư duy hướng tới những điều tốt đẹp và lẽ phải.\n\n\n', 219900.00, 'thieunhi4.jpg'),
(58, 'Câu Chuyện Về Thomas Edison - Giá Trị Của Sự Sáng Tạo\n', 'NXB: Thế giới', 6, 'Thomas Edison – một nhà phát minh vĩ đại, ông đã phát minh ra rất nhiều thiết bị điện có ảnh hưởng lớn tới cuộc sống của người dân trong thế kỷ XX. Các câu chuyện trong cuốn sách được xây dựng với một chút hư cấu về cuộc đời của Thomas Edison thông qua những sự việc đã từng diễn ra trong suốt cuộc đời của ông, để từ đó thấy được giá trị và ý nghĩa của sự sáng tạo.\n\nHans Christian Andersen được coi là một trong những người kể chuyện vĩ đại nhất lịch sử. Ông sớm biểu lộ trí thông minh và óc tưởng tượng tuyệt vời của mình từ khi còn là một cậu bé. Các câu chuyện trong cuốn sách được xây dựng với một chút hư cấu về cuộc đời của Andersen thông qua những sự việc đã từng diễn ra trong suốt cuộc đời của ông, để từ đó thấy được giá trị và ý nghĩa của trí tưởng tượng.', 169900.00, 'thieunhi5.jpg'),
(59, 'Chinh Phục Không Gian - Hành Trình Kỳ Diệu\n', 'NXB: Thế giới', 6, 'Trẻ em luôn khao khát được khám phá thế giới xung quanh mình, đặc biệt các em rất yêu thích vũ trụ. Trái Đất của chúng ta nằm trong trong Vũ trụ vô cùng rộng lớn và có biết bao nhiêu điều thú vị, vĩ đại đã được con người lý giải và chinh phục.\n\nMỗi đứa trẻ đều ước mơ được chinh phục thế giới, chinh phục kiến thức. hãy để con bạn vui học và thỏa mãn với cuốn sách CHINH PHỤC KHÔNG GIAN – HÀNH TRÌNH KỲ DIỆU.\n\nChinh phục không gian có lẽ là cuộc chinh phục kì diệu và vĩ đại nhất mà con người đã và đang thực hiện. Khám phá vũ trụ bao la là ước mơ từ hàng ngàn năm nhưng cho đến thế kỷ thứ 20 nó mới trở nên sôi động hơn bao giờ hết.\n\nNga – Mỹ hai cường quốc đã tạo ra một cuộc chạy đua vào không gian hết sức ngoạn mục, kết quả là hàng loạt cột mốc đã được tạo ra, đánh dấu những bước tiến hết sức quan trọng trong hành trình chinh phục không gian của con người.\n\nNội dung sách tái hiện lại những cột mốc quan trọng trong hành trình chinh phục không gian của con người : Từ việc chế tạo những con tàu vũ trụ đầu tiên, lần đầu tiên con người bay vòng quanh Trái Đất, lần đầu tiên con người đặt chân lên Mặt Trăng, xây dựng trạm vũ trụ quốc tế, …\n\nCùng với việc tái hiện lại hành trình chinh phục không gian cuốn sách còn đề cập đến những hiệu ứng tích cực của quá trình chinh phục không gian lên cuộc sống thường ngày trên Trái Đất cũng như những bước đi tiếp theo của con người trong hành trình chinh phục không gian tương lai.\n\nCuốn sách chắc chắn sẽ giúp con bạn chinh phục được ước mơ và phát huy sự hăng say khám phá, học tập hơn nữa.', 239900.00, 'thieunhi6.jpg'),
(60, 'Ehon Wolfoo - Mắt Tinh Anh, Nhìn Thật Nhanh\n', 'NXB: Dân trí', 6, 'Ehon Wolfoo - Mắt Tinh Anh, Nhìn Thật Nhanh mang đến những bài học bổ ích để trẻ rèn luyện những thói quen tốt liên quan đến mắt trong quá trình học hành và đọc sách. Ngoài ra, Wolfoo cùng các bạn sẽ cho thấy sự dũng cảm đối mặt và khả năng giải quyết vấn đề của trẻ khi đứng trước một câu hỏi hoặc tình huống khó.\n\nWolfoo Ehon sở hữu nội dung và những bài học vô cùng hấp dẫn, được biến tấu dưới dạng các chuyến phiêu lưu của Wolfoo và những người bạn. Trong quá trình đọc, với mỗi hành động và tình huống, trẻ sẽ có cơ hội khám phá, tò mò, biết cách sống trung thực, chan hòa với những người xung quanh, từ đó bồi đắp thêm những cá tính tích cực cho trẻ.', 189900.00, 'thieunhi7.jpg'),
(61, 'Em Học Lập Trình Python\n', 'NXB: Dân trí', 6, 'Pythons là một trong năm ngôn ngữ lập trình chuyên nghiệp phổ biến nhất trên thế giới. Khác với những loại ngôn ngữ lập trình khác thì Pythons giúp các lập trình viên tạo ra những phần mềm hay ứng dụng mạnh mẽ và nhạy bén đáp ứng được nhiều nhu cầu hơn. \n \nVậy trẻ học lập trình Pythons như thế nào? “Em học lập trình pythons” chính là chiếc chìa khóa giải mã mọi bí ẩn của hệ lập trình này. \n- Cuốn sách sẽ giúp các lập trình viên nhí hiểu hơn về các khái niệm, kiến thức cơ bản của lập trình. \n- Các em sẽ được tự tay tạo lập những phần mềm game chuyên nghiệp hay những trang web đơn giản thân thiện với người dùng bằng ngôn ngữ lập trình Pythons. \n- Bên cạnh đó, các em cũng được rèn luyện thêm khả năng tư duy và suy nghĩ logic. Bồi đắp sự tự tin và kỹ năng học tập hiệu quả.', 259900.00, 'thieunhi8.jpg'),
(62, 'Em Học Lập Trình Scratch\n', 'NXB: Dân trí', 6, 'Ngày nay, lập trình được xem là “Ngôn ngữ mới” của tương lai. Các nước phát triển đều đã phổ cập môn học lập trình vào trong các trường học chính quy dành cho các em học sinh Tiểu học.\n\n \n\nĐể trẻ làm quen sớm với lập trình theo phương pháp vừa học- vừa chơi sẽ giúp trẻ phát triển toàn diện khả năng tư duy logic, phản biện, và đặc biệt là rèn luyện kỹ năng tập trung, kiên nhẫn.\n\n \n\nNhưng lập trình là gì? Học lập trình như thế nào? Đều là những thắc mắc chung của rất nhiều phụ huynh và các em nhỏ.\n\n \n\nCuốn sách “Em học lập trình Scratch” sẽ mang đến câu trả lời hoàn hảo cho các em. Scratch là một trong năm ngôn ngữ lập trình đơn giản dành cho trẻ được ứng dụng rộng rãi trên 150 quốc gia trên thế giới và được dịch ra 70 ngôn ngữ khác nhau.\n\n ', 209900.00, 'thieunhi9.jpg'),
(63, 'Ehon Wolfoo - Ai Đánh Cắp Lâu Đài Cát Của Tớ\n', 'NXB: Dân trí', 6, 'Ehon Wolfoo - Ai Đánh Cắp Lâu Đài Cát Của Tớ sẽ khơi dậy sự tò mò ở trẻ và giúp trẻ trải nghiệm niềm vui của hành trình khám phá.\n\nWolfoo Ehon sở hữu nội dung và những bài học vô cùng hấp dẫn, được biến tấu dưới dạng các chuyến phiêu lưu của Wolfoo và những người bạn. Trong quá trình đọc, với mỗi hành động và tình huống, trẻ sẽ có cơ hội khám phá, tò mò, biết cách sống trung thực, chan hòa với những người xung quanh, từ đó bồi đắp thêm những cá tính tích cực cho trẻ.', 159900.00, 'thieunhi10.jpg');

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `categories`
--

CREATE TABLE `categories` (
  `category_id` int(11) NOT NULL,
  `category_name` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Đang đổ dữ liệu cho bảng `categories`
--

INSERT INTO `categories` (`category_id`, `category_name`) VALUES
(1, 'Sách kinh doanh'),
(2, 'Sách kỹ năng'),
(3, 'Sách tâm lý học'),
(4, 'Tiểu thuyết/ Văn học'),
(5, 'Đầu tư tài chính'),
(6, 'Thiếu nhi');

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `memberpayments`
--

CREATE TABLE `memberpayments` (
  `payment_id` int(11) NOT NULL,
  `user_id` int(11) DEFAULT NULL,
  `amount` decimal(10,2) DEFAULT NULL,
  `payment_date` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `orders`
--

CREATE TABLE `orders` (
  `order_id` int(11) NOT NULL,
  `user_id` int(11) DEFAULT NULL,
  `order_date` date DEFAULT NULL,
  `total_amount` decimal(10,2) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `partners`
--

CREATE TABLE `partners` (
  `partner_id` int(11) NOT NULL,
  `partner_name` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `permissions`
--

CREATE TABLE `permissions` (
  `permission_id` int(11) NOT NULL,
  `permission_name` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `posts`
--

CREATE TABLE `posts` (
  `post_id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `content` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `rentals`
--

CREATE TABLE `rentals` (
  `rental_id` int(11) NOT NULL,
  `user_id` int(11) DEFAULT NULL,
  `book_id` int(11) DEFAULT NULL,
  `rental_date` date DEFAULT NULL,
  `due_date` date DEFAULT NULL,
  `return_date` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `userpermissions`
--

CREATE TABLE `userpermissions` (
  `user_id` int(11) DEFAULT NULL,
  `permission_id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `users`
--

CREATE TABLE `users` (
  `user_id` int(11) NOT NULL,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `other_personal_info` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Đang đổ dữ liệu cho bảng `users`
--

INSERT INTO `users` (`user_id`, `username`, `password`, `email`, `other_personal_info`) VALUES
(1, 'admin', '123456', 'admin@example.com', 'Some additional personal info');

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `books`
--
ALTER TABLE `books`
  ADD PRIMARY KEY (`book_id`),
  ADD KEY `category_id` (`category_id`);

--
-- Chỉ mục cho bảng `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`category_id`);

--
-- Chỉ mục cho bảng `memberpayments`
--
ALTER TABLE `memberpayments`
  ADD PRIMARY KEY (`payment_id`),
  ADD KEY `user_id` (`user_id`);

--
-- Chỉ mục cho bảng `orders`
--
ALTER TABLE `orders`
  ADD PRIMARY KEY (`order_id`),
  ADD KEY `user_id` (`user_id`);

--
-- Chỉ mục cho bảng `partners`
--
ALTER TABLE `partners`
  ADD PRIMARY KEY (`partner_id`);

--
-- Chỉ mục cho bảng `permissions`
--
ALTER TABLE `permissions`
  ADD PRIMARY KEY (`permission_id`);

--
-- Chỉ mục cho bảng `posts`
--
ALTER TABLE `posts`
  ADD PRIMARY KEY (`post_id`);

--
-- Chỉ mục cho bảng `rentals`
--
ALTER TABLE `rentals`
  ADD PRIMARY KEY (`rental_id`),
  ADD KEY `user_id` (`user_id`),
  ADD KEY `book_id` (`book_id`);

--
-- Chỉ mục cho bảng `userpermissions`
--
ALTER TABLE `userpermissions`
  ADD KEY `user_id` (`user_id`),
  ADD KEY `permission_id` (`permission_id`);

--
-- Chỉ mục cho bảng `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`user_id`);

--
-- Các ràng buộc cho các bảng đã đổ
--

--
-- Các ràng buộc cho bảng `books`
--
ALTER TABLE `books`
  ADD CONSTRAINT `books_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `categories` (`category_id`);

--
-- Các ràng buộc cho bảng `memberpayments`
--
ALTER TABLE `memberpayments`
  ADD CONSTRAINT `memberpayments_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`);

--
-- Các ràng buộc cho bảng `orders`
--
ALTER TABLE `orders`
  ADD CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`);

--
-- Các ràng buộc cho bảng `rentals`
--
ALTER TABLE `rentals`
  ADD CONSTRAINT `rentals_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`),
  ADD CONSTRAINT `rentals_ibfk_2` FOREIGN KEY (`book_id`) REFERENCES `books` (`book_id`);

--
-- Các ràng buộc cho bảng `userpermissions`
--
ALTER TABLE `userpermissions`
  ADD CONSTRAINT `userpermissions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`),
  ADD CONSTRAINT `userpermissions_ibfk_2` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`permission_id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
